name: TFPALVM
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python=3.7
- pytorch=1.11.0
- scipy=1.7.3
- pip
- pip:
  - pandas==1.3.5
  - numpy==1.21.6
  - openpyxl==3.1.1
  - xlrd==2.0.1
  - matplotlib==3.5.3
  - xlwt==1.3.0